### ISSUE TITLE
Large number of files generated using the Visit Data Collection

### ISSUE THREAD

**Issue by rcarson3** [mfem/mfem#1008]
I recently ran a few simulations where I was making use of the Visit data collection class to visualize and post process my data. These simulations outputted 8 grid functions across 60 times steps and were run on 640 MPI ranks which resulted in roughly 350k files per simulation. Previously while making use of this class, it never occurred to me how many files could be generated while running a large simulation. 

I'm wondering if this large number of file counts could be reduced by using something like hdf5 or some other binary container in order to help reduce this issue where all of the grid functions and the mesh are written into one file rather than separate ones. I could still see an issue as you increase the number of MPI ranks and time steps that output data, but it would at least be less than having each gridfunction and mesh outputted as their own file. 

Also, I haven't looked too closely at the Conduit data collection, but does it have the same issue, or does it package everything into one file per MPI rank?

**Comment by jandrej** [comment]
As far as I remember Conduit should solve that problem. It uses binary output with HDF5.

**Comment by cyrush** [comment]
@rcarson3 @jandrej the conduit data collection should package all of the mesh and field data for each domain into one file per mpi task. 

There are also a few strategies that we could use to write to fewer files than MPI tasks, however those are not implemented yet in MFEM.

**Comment by rcarson3** [comment]
@cyrush  thanks I've been able to get things to compile and run for my application using Conduit.

However, I'm having trouble opening the blueprint files using Visit 3.0 on either my local machine or one of LLNL's clusters. I'm not too sure if this is a problem with either the version of HDF5 (v1.10.15) that I'm using, or if it might be to how I'm having things saved off in ExaConstit or with how things are being linked using cmake.

On my local machine I'm seeing the following error when opening up the files:

```
Pseudocolor:  ()
viewer: An invalid variable (HDF5 Error code-1 Error opening HDF5 file for reading: /Users/carson16/Sim_results/results 2/results/exaconstit_000000/domain_000000.hdf5
) was specified.
```

The error is somewhat similar on the remote machines:

```
HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
  #000: ../../src/H5F.c line 604 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../src/H5Fint.c line 990 in H5F_open(): unable to open file: time = Mon Jul 29 11:32:52 2019
, name = 'results/exaconstit_000000/domain_000000.hdf5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: ../../src/H5FD.c line 992 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: ../../src/H5FDsec2.c line 343 in H5FD_sec2_open(): unable to open file: name = 'results/exaconstit_000000/domain_000000.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
```

I can try rebuilding Conduit without HDF5 support to see if things work then, which it sounds like it should cause things to be written out to JSON instead. 

If you'd (@cyrush) like I can also file an issue on the conduit github page .

**Comment by cyrush** [comment]
@rcarson3 VisIt is compiled against HDF5 1.8.x as such it can't always read files written with newer HDF5 (1.10.x). If possible one easy path to success would be using HDF5 1.8.14 when you write the files. 

JSON files will work, but will be quite slow.

**Comment by rcarson3** [comment]
@cyrush I just tried using HDF 1.8.20 and 1.8.14 but still with no luck. I'm still seeing the same errors within Visit.  Do you know if I might need to compile HDF5 with any specific set of given options for it to work?

Also, I've been avoiding recompiling everything under the IBM compilers with this machine rather than the GNU compilers, but I might have to try that out just so I can see if the included HDF5 library on the machine works, and it's not something wrong with how I've compiled/linking things...

Lastly, it appears that the Conduit data collection within MFEM is only able to output to HDF5 files. It fails at run time when saving things off if you don't build Conduit with HDF5.

**Comment by cyrush** [comment]
@rcarson3 

1.8.14 should be ok, we do configure hdf5 without may bells and whistles, but I think we do expect zlib support. 


What runtime errors do you get when trying to save non-hdf5 files?

**Comment by rcarson3** [comment]
@cyrush okay I'm not too sure the 1.8.14 install I had included zlib support. Also, I just realized that spack is much less intrusive, and so I'm now trying that route out to see how things go rather than rolling everything myself.

The runtime error that is being spit out is the following:

```
terminate called after throwing an instance of 'conduit::Error'
  what():
{
  "file": "/g/g20/carson16/exaconstit/conduit/src/libs/relay/conduit_relay_io.cpp",
  "line": 345,
  "message": "conduit_relay lacks HDF5 support: Failed to save conduit node to path results/exaconstit_000000/domain_000001.hdf5"
}
```
I was just looking around, and it looks like I didn't add a line to updating the protocol to being conduit_json. So, I would say that last issue was my fault for not updating my code for that part. Although, it might be nice if the compiler would automatically change the default construction if conduit wasn't built with hdf5.

**Comment by rcarson3** [comment]
@cyrush  So, I just tried the spack version and I was still running into issues there. Could part of this issue be caused by MFEM not linking to the same version of HDF5 as conduit was built with? I noticed during my most recent build that it appears to be linking to the system version of HDF5 rather than the one that Conduit was linked to during build time?

Also, I'm running into the same issues of not Visit not loading things with the JSON files after fixing my previous bug...

I also edited the serial version of example 1 and added the following lines to test whether it was my application or elsewhere that was causing the bug. These lines were added right before step 14 and are more or less representative of how I'm doing stuff in my code. 

```
   ConduitDataCollection conduit_dc("results/tests", mesh);
   //I tested this with both the json and HDF5 formats
   //conduit_dc.SetProtocol("json");                                                                           
   conduit_dc.RegisterField("solution",  &x);
   conduit_dc.SetCycle(0);
   conduit_dc.SetTime(0.0);
   conduit_dc.Save();
```

It failed on me both times but at different points. The JSON version failed to load in visit v3.0 and visit v2.13.3, and the HDF5 failed at while writing the file with the following error:

```
terminate called after throwing an instance of 'conduit::Error'
  what():  
{
  "file": ".../spack-src/src/libs/relay/conduit_relay_io_hdf5.cpp",
  "line": 1989,
  "message": "HDF5 Error code-1 Failed to create H5P_FILE_CREATE  property list"
}
```
which I'm wondering if this is caused by MFEM not linking to the same version of HDF5 that Conduit was built with at least when building MFEM with CMAKE. However, I will say that my application didn't have this problem since I used the information provided by Conduit's cmake config file to link to the version of HDF5 that was used during build time.

I've tested the above using version 0.3.1 and the master branch of Conduit with no success.

**Comment by v-dobrev** [comment]
@rcarson3,

If you suspect that the version of HDF5 that MFEM is linked against is the issue, you can point cmake to find the specific version you need by setting the cmake variable `HDF5_ROOT` during configuration, e.g. something like this:
```console
cmake -DHDF5_ROOT:PATH=/path/to/hdf5 ...
```
I have not tried this myself but this is what the HDF5 module that comes with cmake says: https://cmake.org/cmake/help/latest/module/FindHDF5.html

**Comment by rcarson3** [comment]
@v-dobrev that helped to get my serial version of example 1 that made use of HDF5 and Conduit to run. However, it appears the data set is still failing to load within Visit. If y'all (@cyrush  and @v-dobrev ) would like I can send you the files generated from example 1 although maybe with a lower refinement level, so it's easier to examine and maybe spot if there's something wrong in there.

**Comment by v-dobrev** [comment]
It looks like the path inside the root file saved by the Conduit data collection is wrong: I'm getting this error in VisIt:
```ascii
Pseudocolor:  ()
viewer: An invalid variable (HDF5 Error code-1 Error opening HDF5 file for reading: /Users/dobrev1/code/mfem/examples/results/results/tests_000000/domain_000000.hdf5
) was specified.
```
and the actual file is here:
```
/Users/dobrev1/code/mfem/examples/results/tests_000000/domain_000000.hdf5
```
This is an issue we need to fix. For now, removing the prefix path `results/` from the string `"results/tests"` circumvents the issue and VisIt can load the data.

**Comment by v-dobrev** [comment]
One possible solution is to remove the `prefix_path` from the result of this method: https://github.com/mfem/mfem/blob/369fc7c903398a86588788cef687596dff85d56f/fem/conduitdatacollection.cpp#L915-L929

@cyrush, is this the right way to fix the issue?

**Comment by rcarson3** [comment]
Thanks @v-dobrev that temporary fix should work for me. Also, I was taking a look at the Visit data collection, and it appears to strip off the prefix path from the results, or at least it appears to based on my previous use of it and providing it also something along the lines of ```results/tests```

**Comment by cyrush** [comment]
@v-dobrev @rcarson3, a bit pressed for time over the next week or so, but I would be happy to dive in towards the end of next week.

**Comment by v-dobrev** [comment]
@rcarson3,

Did you see any problems when using the VisIt data collection?

In my test, the VisIt data collection worked correctly. It does split the collection name `"results/tests"` string into `prefix_path` (=`"results/"`) and `name` (=`"tests"`) but they are later merged to form file names. This separation allows you to set the prefix path separately with the `SetPrefixPath` method. It is also needed to create any directories that do not exist.

**Comment by rcarson3** [comment]
@v-dobrev I haven't had any problems using the VisIt data collection outside of the large number of file creations. It's always loaded up just fine in VisIt for me.

**Comment by tzanio** [comment]
@rcarson3 -- what is the status of this issue? Are the any remaining action items for MFEM or @cyrush?

**Comment by rcarson3** [comment]
@tzanio I'd say that this issue is more or less ready to close once the prefix path issue for ```ConduitDataCollection``` is fixed potentially with @v-dobrev proposed fix down below. Then, as far as I can tell, Conduit can pretty much act as a drop in replacement for the ```VisitDataCollection```.

> One possible solution is to remove the `prefix_path` from the result of this method:
> 
> https://github.com/mfem/mfem/blob/369fc7c903398a86588788cef687596dff85d56f/fem/conduitdatacollection.cpp#L915-L929
> 
> @cyrush, is this the right way to fix the issue?

**Comment by tzanio** [comment]
ping: @cyrush
