### ISSUE TITLE
Errors in DGTraceIntegrator Documentation & Examples

### ISSUE THREAD

**Issue by wcdawn** [mfem/mfem#1896]
I had been using the Doxygen documentation and there is an error for the `BilinearFormIntegrator::DGTraceIntegrator`.
The integrator is actually implemented as `(alpha/2) < rho_u (u.n) {v},[w] > + beta < rho_u |u.n| [v],[w] >`.
The documentation omits the factor of `0.5`.
Note that the documentation is correct for the closely related `LinearFormIntegrator::BoundaryFlowIntegrator`.

Tangentially related, the use of `DGTraceIntegrator` in `ex9.cpp` is incorrect.
The factors should be `1.0` and `0.5` near [here](https://github.com/mfem/mfem/blob/533b45cabdd8d6680e3a13a857ee4eb979cf3720/examples/ex9.cpp#L295). Currently, the example flips the sign for one of the factors but this error is not observed because the inflow condition is set to zero.

I can create a PR for these changes if interested.

**Comment by pazner** [comment]
Perhaps the factor of 0.5 is included in the average `{v}` in the first term?

**Comment by wcdawn** [comment]
Unfortunately, no. The user-specified value `alpha` is multiplied by `0.5` in the DGTraceIntegrator and this is not noted in the documentation.

Please see the [documenation](https://github.com/mfem/mfem/blob/533b45cabdd8d6680e3a13a857ee4eb979cf3720/fem/bilininteg.hpp#L2653) and the [code](https://github.com/mfem/mfem/blob/533b45cabdd8d6680e3a13a857ee4eb979cf3720/fem/bilininteg.cpp#L2669).

**Comment by pazner** [comment]
The documentation indicates that the first term is given by `alpha < rho_u (u.n) {v},[w] >`, which is equal to `alpha/2 < rho_u (u.n) (v_m + v_p), (w_m - w_p) >`, where the `m` and `p` subscripts indicate the two neighboring elements of the given face.

It looks like the code is defining `a = 0.5 * alpha * un`, and then multiplying this coefficient by the remaining terms `w rho_u (v_m + v_p), (w_m - w_p)` to compute the integral.

**Comment by wcdawn** [comment]
Maybe? I am using this with H1 finite elements and I'm not very familiar with DG. Regardless, to get the correct (analytic) solution, I had to supply `alpha=1.0` when it should have been `alpha=0.5`.

1. If this is correct for DG but not continuous finite elements, this should at least be noted in the documentation.
1. If this is correct, why is `ex9` written as it is with a doubled `alpha` value?

**Comment by pazner** [comment]
I think the documentation is correct, it's just a matter of noticing that `{v} = 0.5*(v_m + v_p)`, and then factoring out the 0.5. Note that for the `BoundaryFlowIntegrator`, none of the quantities are averaged since everything is single-valued on the boundary (even in the DG case), and so the corresponding factor of 0.5 is written explicitly.

I'm not sure what you mean by a "doubled `alpha` value"? `alpha = 1` is the standard choice, and `beta = -0.5` corresponds to upwinding (other values of `beta` can also be valid for stabilization).

Since you are using H1 elements, the trace integrator will be zero everywhere in the interior of the domain. Are you using it for boundary conditions?

**Comment by v-dobrev** [comment]
The values of `alpha` and `beta` used in ex9/ex9p are correct, even for non-homogeneous inflow b.c. As an example, you can try adding 1 to the initial condition and the inflow b.c. with a patch like this:
```diff
diff --git a/examples/ex9.cpp b/examples/ex9.cpp
index c8a6e7083..ea6728616 100644
--- a/examples/ex9.cpp
+++ b/examples/ex9.cpp
@@ -583,7 +583,7 @@ double u0_function(const Vector &x)
                   ry *= s;
                }
                return ( erfc(w*(X(0)-cx-rx))*erfc(-w*(X(0)-cx+rx)) *
-                        erfc(w*(X(1)-cy-ry))*erfc(-w*(X(1)-cy+ry)) )/16;
+                        erfc(w*(X(1)-cy-ry))*erfc(-w*(X(1)-cy+ry)) )/16 + 1.0;
             }
          }
       }
@@ -611,7 +611,7 @@ double inflow_function(const Vector &x)
       case 0:
       case 1:
       case 2:
-      case 3: return 0.0;
+      case 3: return 1.0;
    }
    return 0.0;
 }
```
Then run this on a non-periodic mesh, e.g.:
```console
./ex9 -m ../data/inline-quad.mesh -p 0 -r 2 -dt 0.001 -tf 0.75
```
You can also shift the inflow b.c. -- in that case there will be visible oscillations (because of the discontinuity and the lack of monotonicity treatment) however you should still see that the correct value of 1 is being introduced at the inflow boundary.

The full derivation of why these are the correct values for `alpha` and `beta` is a bit tricky and involves integration by parts twice. If you want, I can try to summarize it here.

The important observation here is that the equation being solved by ex9/ex9p is `du/dt + v \cdot grad(u) = 0`. If you are solving the conservation equation `du/dt + div(v u) = 0` then the bilinear and linear forms will be different.

**Comment by v-dobrev** [comment]
By the way, to try this (non-homogeneous inflow b.c.) with continuous elements, you can make the following changes in ex9:
```diff
diff --git a/examples/ex9.cpp b/examples/ex9.cpp
index c8a6e7083..8ef0aa879 100644
--- a/examples/ex9.cpp
+++ b/examples/ex9.cpp
@@ -260,7 +260,8 @@ int main(int argc, char *argv[])
 
    // 5. Define the discontinuous DG finite element space of the given
    //    polynomial order on the refined mesh.
-   DG_FECollection fec(order, dim, BasisType::GaussLobatto);
+   // DG_FECollection fec(order, dim, BasisType::GaussLobatto);
+   H1_FECollection fec(order, dim);
    FiniteElementSpace fes(&mesh, &fec);
 
    cout << "Number of unknowns: " << fes.GetVSize() << endl;
@@ -291,8 +292,8 @@ int main(int argc, char *argv[])
    }
    m.AddDomainIntegrator(new MassIntegrator);
    k.AddDomainIntegrator(new ConvectionIntegrator(velocity, -1.0));
-   k.AddInteriorFaceIntegrator(
-      new TransposeIntegrator(new DGTraceIntegrator(velocity, 1.0, -0.5)));
+   // k.AddInteriorFaceIntegrator(
+   //    new TransposeIntegrator(new DGTraceIntegrator(velocity, 1.0, -0.5)));
    k.AddBdrFaceIntegrator(
       new TransposeIntegrator(new DGTraceIntegrator(velocity, 1.0, -0.5)));
 
@@ -583,7 +584,7 @@ double u0_function(const Vector &x)
                   ry *= s;
                }
                return ( erfc(w*(X(0)-cx-rx))*erfc(-w*(X(0)-cx+rx)) *
-                        erfc(w*(X(1)-cy-ry))*erfc(-w*(X(1)-cy+ry)) )/16;
+                        erfc(w*(X(1)-cy-ry))*erfc(-w*(X(1)-cy+ry)) )/16 + 1.0;
             }
          }
       }
@@ -611,7 +612,7 @@ double inflow_function(const Vector &x)
       case 0:
       case 1:
       case 2:
-      case 3: return 0.0;
+      case 3: return 1.0;
    }
    return 0.0;
 }
```
You will probably notice that the continuous version has a bit more oscillations than the DG version -- that is why the DG formulation is typically preferred for this type of equations.

**Comment by wcdawn** [comment]
@pazner Yes. This is being used as a boundary condition for the weak-form. I'm solving a second-order particle transport problem. Specifically, Self-Adjoint Angular Flux (SAAF).

@v-dobrev Thank you for the information. Yes, H1 is susceptible to oscillations for the pure convection problem. I still don't see why these coefficients are correct. It could be related to something DG that I have not encountered but my understanding is related to Green's second identity.

<img src="https://i.upmath.me/svg/%5Cint_%5COmega%20%5Cmathbf%7Bv%7D%20%5Ccdot%20%5Cnabla%20u%20%5C%2C%20w%20%5C%3B%20d%5COmega%20%3D%200" alt="\int_\Omega \mathbf{v} \cdot \nabla u \, w \; d\Omega = 0" />

<img src="https://i.upmath.me/svg/%5Cint_%5COmega%20%5Cmathbf%7Bv%7D%20%5Ccdot%20%5Cnabla%20u%20%5C%2C%20w%20%5C%3B%20d%5COmega%20%3D%20%5Cint_%5CGamma%20u%20%5C%2C%20w%20%5C%2C%20%5Cmathbf%7Bv%7D%20%5Ccdot%20%5Cmathbf%7Bn%7D%20%5C%3B%20d%5CGamma%20-%20%5Cint_%5COmega%20u%20%5C%2C%20%5Cnabla%20%5Ccdot%20(%20w%20%5Cmathbf%7Bv%7D%20)%20%5C%3B%20d%5COmega%20" alt="\int_\Omega \mathbf{v} \cdot \nabla u \, w \; d\Omega = \int_\Gamma u \, w \, \mathbf{v} \cdot \mathbf{n} \; d\Gamma - \int_\Omega u \, \nabla \cdot ( w \mathbf{v} ) \; d\Omega " />

<img src="https://i.upmath.me/svg/%20-%20%5Cint_%5COmega%20u%20%5C%2C%20%5Cnabla%20%5Ccdot%20(%20w%20%5Cmathbf%7Bv%7D%20)%20%5C%3B%20d%5COmega%20%2B%20%5Cint_%5CGamma%20u%20%5C%2C%20w%20%5C%2C%20%5Cmathbf%7Bv%7D%20%5Ccdot%20%5Cmathbf%7Bn%7D%20%5C%3B%20d%5CGamma%20%3D%200" alt=" - \int_\Omega u \, \nabla \cdot ( w \mathbf{v} ) \; d\Omega + \int_\Gamma u \, w \, \mathbf{v} \cdot \mathbf{n} \; d\Gamma = 0" />


<img src="https://i.upmath.me/svg/%20-%20%5Cint_%5COmega%20u%20%5C%2C%20%5Cnabla%20%5Ccdot%20(%20w%20%5Cmathbf%7Bv%7D%20)%20%5C%3B%20d%5COmega%20%2B%20%5Cint_%7B%5Csubstack%7B%5CGamma%20%5C%5C%20%5Cmathbf%7Bv%7D%20%5Ccdot%20%5Cmathbf%7Bn%7D%20%3E%200%20%7D%7D%20u%20%5C%2C%20w%20%5C%2C%20%5Cmathbf%7Bv%7D%20%5Ccdot%20%5Cmathbf%7Bn%7D%20%5C%3B%20d%5CGamma%20%3D%20-%20%5Cint_%7B%5Csubstack%7B%5CGamma%20%5C%5C%20%5Cmathbf%7Bv%7D%20%5Ccdot%20%5Cmathbf%7Bn%7D%20%3C%200%20%7D%7D%20u%5E%7B%5Ctext%7Binflow%7D%7D%20%5C%2C%20w%20%5C%2C%20%5Cmathbf%7Bv%7D%20%5Ccdot%20%5Cmathbf%7Bn%7D%20%5C%3B%20d%5CGamma%20" alt=" - \int_\Omega u \, \nabla \cdot ( w \mathbf{v} ) \; d\Omega + \int_{\substack{\Gamma \\ \mathbf{v} \cdot \mathbf{n} &gt; 0 }} u \, w \, \mathbf{v} \cdot \mathbf{n} \; d\Gamma = - \int_{\substack{\Gamma \\ \mathbf{v} \cdot \mathbf{n} &lt; 0 }} u^{\text{inflow}} \, w \, \mathbf{v} \cdot \mathbf{n} \; d\Gamma " />

My main point is, for my problem, I want to evaluate the outflow boundary condition (<img src="https://i.upmath.me/svg/%5Cmathbf%7Bv%7D%20%5Ccdot%20%5Cmathbf%7Bn%7D%20%3E%200" alt="\mathbf{v} \cdot \mathbf{n} &gt; 0" />)
```
0.5*< (u.n) {v},[w] > + 0.5*< |u.n| [v],[w] >
```
and to do this with H1 elements, I have to set `alpha=1.0` and `beta=0.5` and this is inconsistent with the documentation.

**Comment by v-dobrev** [comment]
The documentation does not fully explain the notation used in the description of the forms. Let me try to be more specific. First, for interior faces: `n` is assumed to be the normal vector pointing from element 1 to element 2 and then the average, `{v}`, and jump, `[v]`, are defined as:
```ascii
{v} = (v1 + v2)/2
[v] = (v1 - v2)
```
where `v1`, `v2` are the values of `v` on element 1 and element 2, respectively.
On the boundary, `n` is the outward normal vector and the definitions of `{v}` and `[v]` simply take `v2 = 0`.

Applying these formulas to `DGTraceIntegrator` with `alpha = 1` and `beta = 1/2`, on the boundary, gives (u is the velocity field, v is the trial function, w is the test function):
```ascii
< (u.n) (v1 + v2)/2, (w1 - w2) > + (1/2) < |u.n| (v1 - v2), (w1 - w2) > =
   = (1/2) <(u.n) v1, w1> + (1/2) < |u.n| v1, w1 > =
   = < (u.n) v1, w1 >_{outflow}
```
Does this make sense?

**Comment by wcdawn** [comment]
This makes a lot more sense. I was not familiar with this notation.

Could we add something like
```
{v} = (v1 + v2)/2
[v] = (v1 - v2)
and
v2 = 0 on boundaries
```
to the documentation?
Adding a note that `alpha=1` with `beta=0.5` corresponds to outflow would be preferable to me but I realize this may not have as broad applicability.

**Comment by v-dobrev** [comment]
I see no harm in adding more details in the docs. 😄

**Comment by pazner** [comment]
For what it's worth, I think there are two related steps we could take to reduce the confusion:

* Implement a convection integrator in conservative form. There are a lot of applications where this form is by far more common, and so it would save the extra step of integrating by parts and compensating for the additional boundary terms.
* Implement the transpose of the DG trace integrator directly. The most prominent application of the DG trace integrator is ex9 and related DG advection application, which always use the transpose… this extra step just makes it confusing.

**Comment by v-dobrev** [comment]
> Implement a convection integrator in conservative form.

We can already handle this with `DGTraceIntegrator`. One option is to add to the documentation of `DGTraceIntegrator` and maybe `ConvectionIntegrator` what the right ways are to use them for these common cases.

Adding new integrators that avoid the need for transposing is certainly an option, if you think that will make it easier for users.

**Comment by pazner** [comment]
> We can already handle this with `DGTraceIntegrator`. One option is to add to the documentation of `DGTraceIntegrator` and maybe `ConvectionIntegrator` what the right ways are to use them for these common cases.

Yes, of course this is already possible using the existing integrators, but because of the integration by parts, it's only exactly equivalent if the quadrature is exact or with some sort of summation by parts property. Perhaps more importantly, recasting the problem in non-conservative form can be a bit unintuitive and requires some pencil-and-paper derivations. It could be nice to have a (for example) `ConservativeConvectionIntegrator` that implements directly `u*vel*grad(v)` (I suppose it could simply be a wrapper for the transpose of the standard `ConvectionIntegrator`), so that the notation in MFEM can more closely match the conservative form of the equations that is commonly used in DG papers.

**Comment by v-dobrev** [comment]
> Yes, of course this is already possible using the existing integrators, but because of the integration by parts, it's only exactly equivalent if the quadrature is exact or with some sort of summation by parts property.

I'm not sure I quite understand what is "only exactly equivalent if ...". What are the two things that you compare here?

> ... recasting the problem in non-conservative form can be a bit unintuitive and requires some pencil-and-paper derivations.

This is true. That is why I suggested to add this case (and the conservative form case) to the documentation of `ConvectionIntegrator` and `DGTraceIntegrator`. Of course, even now we have example 9/9p which is an illustration of exactly this non-conservative formulation.

For the conservative case we need `ConvectionIntegrator` (transposed) and `DGTraceIntegrator`. For completeness, here is the discretization I have in mind:
```ascii
  - (div(v u), w) =
= - \sum_K (div(v u), w)_K =
= - \sum_K ( <v.n u, w>_{\partial K} - (v u, grad(w))_K ) =
= \sum_K (v u, grad(w))_K - \sum_F ( <v1.n1 u1, w1>_F + <v2.n2 u2, w2>_F ) =
= [ set n = n1 = -n2, assume v1.n = v2.n ] =
= \sum_K (v u, grad(w))_K - \sum_F ( <v.n u1, w1>_F - <v.n u2, w2>_F )
```
At this point, on the faces, we replace the discontinuous flux `(v u)` with a consistent single valued flux `(v u*)` and we get (this is no longer equal to the above expression):
```ascii
  \sum_K (v u, grad(w))_K - \sum_F ( <v.n u*, w1>_F - <v.n u*, w2>_F ) =
= \sum_K (v u, grad(w))_K - \sum_F <v.n u*, [w]>_F
```
The typical choice for for `u*` is the upwind value:
```ascii
u_upwind = / u2, v.n < 0
           \ u1, v.n > 0
```
which when multiplied by `v.n` can be written as `v.n u_upwind = v.n {u} + 1/2 |v.n| [u]` resulting in the form:
```ascii
\sum_K (v u, grad(w))_K - \sum_F ( <v.n {u} + 1/2 |v.n| [u], [w]>_F )
```
which is exactly `ConvectionIntegrator` transposed and `DGTraceIntegrator`.

> It could be nice to have a (for example) `ConservativeConvectionIntegrator` that implements directly `u*vel*grad(v)` ...

Sounds good to me: as I said earlier, I have no problem with adding transpose integrators like this.

**Comment by pazner** [comment]
> > Yes, of course this is already possible using the existing integrators, but because of the integration by parts, it's only exactly equivalent if the quadrature is exact or with some sort of summation by parts property.
> 
> I'm not sure I quite understand what is "only exactly equivalent if ...". What are the two things that you compare here?

I thought you were referring to using the (non-transposed) `ConvectionIntegrator` together with transposed `DGTraceIntegrator` like in example 9, which I was comparing to "directly" implementing the conservative form (e.g. with the transpose of the `ConvectionIntegrator`).

Yes, I agree completely with what you wrote. I was just advocating for making the transposed integrators more visible (i.e. giving them their own class names), and also possibly filling in some of the gaps, e.g. the PA transposed action of the convection integrator.

**Comment by tzanio** [comment]
> Yes, I agree completely with what you wrote. I was just advocating for making the transposed integrators more visible (i.e. giving them their own class names), and also possibly filling in some of the gaps, e.g. the PA transposed action of the convection integrator.

I agree with Will here.

**Comment by tzanio** [comment]
Resolved by https://github.com/mfem/mfem/pull/1901.
