### ISSUE TITLE
Mesh::MakePeriodic() with NURBS meshes

### ISSUE THREAD

**Issue by marc-85** [mfem/mfem#2658]
Hello MFEM community!

I have been trying to transform a NURBS mesh into another NURBS mesh with periodic boundaries. I have started with a 2D square mesh to start with. In order to convert to periodic I am using the `Mesh::MakePeriodic()` function which returns indeed a periodic mesh. The issue is that the returned mesh is no longer a NURBS mesh. Digging into this function I have realized that the mesh stops being NURBS when `Mesh::SetCurvature()` is called.

I have tried commenting out the call to `SetCurvature` but then the output mesh is no longer periodic. Any suggestions as to what I could do?

Many thanks in advance

This is the mesh that I am trying to convert:
```
MFEM NURBS mesh v1.0
dimension 
2

elements
9
1 3 0 1 2 3
1 3 1 4 5 2
1 3 4 6 7 5
1 3 3 2 8 9
1 3 2 5 10 8
1 3 5 7 11 10
1 3 9 8 12 13
1 3 8 10 14 12
1 3 10 11 15 14


boundary
12
1 1 0 1
2 1 0 3
3 1 6 7
4 1 13 12
1 1 1 4
2 1 3 9
3 1 7 11
4 1 12 14
1 1 4 6
2 1 9 13
3 1 11 15
4 1 14 15


edges
24
1 0 3
1 1 2
0 0 1
0 3 2
1 4 5
0 1 4
0 2 5
1 6 7
0 4 6
0 5 7
1 3 9
1 2 8
0 9 8
1 5 10
0 8 10
1 7 11
0 10 11
1 9 13
1 8 12
0 13 12
1 10 14
0 12 14
1 11 15
0 14 15


vertices
16


patches

#patch  0
knotvectors
2
3 4 0 0 0 0 1 1 1 1
3 4 0 0 0 0 1 1 1 1

dimensions
2

controlpoints
-1.0 -1.0 1
-0.7777777777777778 -1.0 1
-0.5555555555555556 -1.0 1
-0.33333333333333337 -1.0 1
-1.0 -0.7777777777777778 1
-0.7777777777777778 -0.7777777777777778 1
-0.5555555555555556 -0.7777777777777778 1
-0.33333333333333337 -0.7777777777777778 1
-1.0 -0.5555555555555556 1
-0.7777777777777778 -0.5555555555555556 1
-0.5555555555555556 -0.5555555555555556 1
-0.33333333333333337 -0.5555555555555556 1
-1.0 -0.33333333333333337 1
-0.7777777777777778 -0.33333333333333337 1
-0.5555555555555556 -0.33333333333333337 1
-0.33333333333333337 -0.33333333333333337 1


#patch  1
knotvectors
2
3 4 0 0 0 0 1 1 1 1
3 4 0 0 0 0 1 1 1 1

dimensions
2

controlpoints
-0.33333333333333337 -1.0 1
-0.11111111111111116 -1.0 1
0.11111111111111105 -1.0 1
0.33333333333333326 -1.0 1
-0.33333333333333337 -0.7777777777777778 1
-0.11111111111111116 -0.7777777777777778 1
0.11111111111111105 -0.7777777777777778 1
0.33333333333333326 -0.7777777777777778 1
-0.33333333333333337 -0.5555555555555556 1
-0.11111111111111116 -0.5555555555555556 1
0.11111111111111105 -0.5555555555555556 1
0.33333333333333326 -0.5555555555555556 1
-0.33333333333333337 -0.33333333333333337 1
-0.11111111111111116 -0.33333333333333337 1
0.11111111111111105 -0.33333333333333337 1
0.33333333333333326 -0.33333333333333337 1


#patch  2
knotvectors
2
3 4 0 0 0 0 1 1 1 1
3 4 0 0 0 0 1 1 1 1

dimensions
2

controlpoints
0.33333333333333326 -1.0 1
0.5555555555555555 -1.0 1
0.7777777777777777 -1.0 1
0.9999999999999999 -1.0 1
0.33333333333333326 -0.7777777777777778 1
0.5555555555555555 -0.7777777777777778 1
0.7777777777777777 -0.7777777777777778 1
0.9999999999999999 -0.7777777777777778 1
0.33333333333333326 -0.5555555555555556 1
0.5555555555555555 -0.5555555555555556 1
0.7777777777777777 -0.5555555555555556 1
0.9999999999999999 -0.5555555555555556 1
0.33333333333333326 -0.33333333333333337 1
0.5555555555555555 -0.33333333333333337 1
0.7777777777777777 -0.33333333333333337 1
0.9999999999999999 -0.33333333333333337 1


#patch  3
knotvectors
2
3 4 0 0 0 0 1 1 1 1
3 4 0 0 0 0 1 1 1 1

dimensions
2

controlpoints
-1.0 -0.33333333333333337 1
-0.7777777777777778 -0.33333333333333337 1
-0.5555555555555556 -0.33333333333333337 1
-0.33333333333333337 -0.33333333333333337 1
-1.0 -0.11111111111111116 1
-0.7777777777777778 -0.11111111111111116 1
-0.5555555555555556 -0.11111111111111116 1
-0.33333333333333337 -0.11111111111111116 1
-1.0 0.11111111111111105 1
-0.7777777777777778 0.11111111111111105 1
-0.5555555555555556 0.11111111111111105 1
-0.33333333333333337 0.11111111111111105 1
-1.0 0.33333333333333326 1
-0.7777777777777778 0.33333333333333326 1
-0.5555555555555556 0.33333333333333326 1
-0.33333333333333337 0.33333333333333326 1


#patch  4
knotvectors
2
3 4 0 0 0 0 1 1 1 1
3 4 0 0 0 0 1 1 1 1

dimensions
2

controlpoints
-0.33333333333333337 -0.33333333333333337 1
-0.11111111111111116 -0.33333333333333337 1
0.11111111111111105 -0.33333333333333337 1
0.33333333333333326 -0.33333333333333337 1
-0.33333333333333337 -0.11111111111111116 1
-0.11111111111111116 -0.11111111111111116 1
0.11111111111111105 -0.11111111111111116 1
0.33333333333333326 -0.11111111111111116 1
-0.33333333333333337 0.11111111111111105 1
-0.11111111111111116 0.11111111111111105 1
0.11111111111111105 0.11111111111111105 1
0.33333333333333326 0.11111111111111105 1
-0.33333333333333337 0.33333333333333326 1
-0.11111111111111116 0.33333333333333326 1
0.11111111111111105 0.33333333333333326 1
0.33333333333333326 0.33333333333333326 1


#patch  5
knotvectors
2
3 4 0 0 0 0 1 1 1 1
3 4 0 0 0 0 1 1 1 1

dimensions
2

controlpoints
0.33333333333333326 -0.33333333333333337 1
0.5555555555555555 -0.33333333333333337 1
0.7777777777777777 -0.33333333333333337 1
0.9999999999999999 -0.33333333333333337 1
0.33333333333333326 -0.11111111111111116 1
0.5555555555555555 -0.11111111111111116 1
0.7777777777777777 -0.11111111111111116 1
0.9999999999999999 -0.11111111111111116 1
0.33333333333333326 0.11111111111111105 1
0.5555555555555555 0.11111111111111105 1
0.7777777777777777 0.11111111111111105 1
0.9999999999999999 0.11111111111111105 1
0.33333333333333326 0.33333333333333326 1
0.5555555555555555 0.33333333333333326 1
0.7777777777777777 0.33333333333333326 1
0.9999999999999999 0.33333333333333326 1


#patch  6
knotvectors
2
3 4 0 0 0 0 1 1 1 1
3 4 0 0 0 0 1 1 1 1

dimensions
2

controlpoints
-1.0 0.33333333333333326 1
-0.7777777777777778 0.33333333333333326 1
-0.5555555555555556 0.33333333333333326 1
-0.33333333333333337 0.33333333333333326 1
-1.0 0.5555555555555555 1
-0.7777777777777778 0.5555555555555555 1
-0.5555555555555556 0.5555555555555555 1
-0.33333333333333337 0.5555555555555555 1
-1.0 0.7777777777777777 1
-0.7777777777777778 0.7777777777777777 1
-0.5555555555555556 0.7777777777777777 1
-0.33333333333333337 0.7777777777777777 1
-1.0 0.9999999999999999 1
-0.7777777777777778 0.9999999999999999 1
-0.5555555555555556 0.9999999999999999 1
-0.33333333333333337 0.9999999999999999 1


#patch  7
knotvectors
2
3 4 0 0 0 0 1 1 1 1
3 4 0 0 0 0 1 1 1 1

dimensions
2

controlpoints
-0.33333333333333337 0.33333333333333326 1
-0.11111111111111116 0.33333333333333326 1
0.11111111111111105 0.33333333333333326 1
0.33333333333333326 0.33333333333333326 1
-0.33333333333333337 0.5555555555555555 1
-0.11111111111111116 0.5555555555555555 1
0.11111111111111105 0.5555555555555555 1
0.33333333333333326 0.5555555555555555 1
-0.33333333333333337 0.7777777777777777 1
-0.11111111111111116 0.7777777777777777 1
0.11111111111111105 0.7777777777777777 1
0.33333333333333326 0.7777777777777777 1
-0.33333333333333337 0.9999999999999999 1
-0.11111111111111116 0.9999999999999999 1
0.11111111111111105 0.9999999999999999 1
0.33333333333333326 0.9999999999999999 1


#patch  8
knotvectors
2
3 4 0 0 0 0 1 1 1 1
3 4 0 0 0 0 1 1 1 1

dimensions
2

controlpoints
0.33333333333333326 0.33333333333333326 1
0.5555555555555555 0.33333333333333326 1
0.7777777777777777 0.33333333333333326 1
0.9999999999999999 0.33333333333333326 1
0.33333333333333326 0.5555555555555555 1
0.5555555555555555 0.5555555555555555 1
0.7777777777777777 0.5555555555555555 1
0.9999999999999999 0.5555555555555555 1
0.33333333333333326 0.7777777777777777 1
0.5555555555555555 0.7777777777777777 1
0.7777777777777777 0.7777777777777777 1
0.9999999999999999 0.7777777777777777 1
0.33333333333333326 0.9999999999999999 1
0.5555555555555555 0.9999999999999999 1
0.7777777777777777 0.9999999999999999 1
0.9999999999999999 0.9999999999999999 1
```

**Comment by tzanio** [comment]
ping: @IdoAkkerman, @JacobLotz

**Comment by JacobLotz** [comment]
Sorry for my late reply. My email does not seem to give notifications anymore...
I only make periodic NURBS meshes. For the specific case of NURBS meshes I can maybe help, but for the general case for all meshes problably not. 

I make my NURBS meshes periodic by using master and slave boundaries. I have used two different ways:

1) The easiest way to do this is specifying the master and slave at the end of your NURBS-mesh file. 

When the mesh is read by `NURBSExtension::NURBSExtension(std::istream &input)` it reads the master and slave boundary after "periodic" in you mesh file. I think an example is (where I copy only the last part of your mesh):

```
#patch  8
knotvectors
2
3 4 0 0 0 0 1 1 1 1
3 4 0 0 0 0 1 1 1 1

dimensions
2

controlpoints
0.33333333333333326 0.33333333333333326 1
0.5555555555555555 0.33333333333333326 1
0.7777777777777777 0.33333333333333326 1
0.9999999999999999 0.33333333333333326 1
0.33333333333333326 0.5555555555555555 1
0.5555555555555555 0.5555555555555555 1
0.7777777777777777 0.5555555555555555 1
0.9999999999999999 0.5555555555555555 1
0.33333333333333326 0.7777777777777777 1
0.5555555555555555 0.7777777777777777 1
0.7777777777777777 0.7777777777777777 1
0.9999999999999999 0.7777777777777777 1
0.33333333333333326 0.9999999999999999 1
0.5555555555555555 0.9999999999999999 1
0.7777777777777777 0.9999999999999999 1
0.9999999999999999 0.9999999999999999 1

periodic
1
2


```
Here I make the boundaries 1 and 2 periodic.


2) Another way to make a periodic nurbs mesh is indicated in "miniapps/nurbs/nurbs_ex1.cpp"  at lines 211-243. There the NURBSmesh is first read and then made periodic using: `NURBSext->ConnectBoundaries(master,slave);`


I hope this helps! Unfortunately I cannot help you with the functions you mention in mesh.cpp as I have never used them.

**Comment by tzanio** [comment]
Thanks @JacobLotz !

**Comment by marc-85** [comment]
Hi @JacobLotz 

Thanks for your answer!
These do not seem to work for me. In the first case, I have 4 boundaries where boundary 1 should be periodic with 4 and 2 with 3. If I write
```
periodic
1
4
2
3
```
the mesh is read normally but the solution is not periodic and it ends up crashing because no BC is specified. I have also tried with only 1 and 4, i.e.
```
periodic
1
4
```
but the same thing happens and 1 and 4 are not periodic in the solution.

This is what happens with the second approach.  I have written this in my code:
```
Mesh *old_mesh = new Mesh(mesh_file, 1, 1);
Array<int> master(2), slave(2);
master[0] = 1;
master[1] = 2;
slave[0] = 4;
slave[1] = 3;
old_mesh->NURBSext->ConnectBoundaries(master,slave);
```
When run this I get the following error message:
```
Assertion failed: (nsize>=0) is false:
 --> Size must be non-negative.  It is -90
 ... in function: void mfem::Array<T>::SetSize(int) [with T = int]
 ... in file: general/array.hpp:676

application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
```
What is it that I'm doing wrong? 
Very many thanks!

**Comment by JacobLotz** [comment]
Hi Marc,
There is a bug in parallel which is fixed in the branch nurbs-knot2edge. I was able to create a periodic mesh in miniapps/nurbs/nurbs_ex1 by defining the master and slave as an input. See output below.

Are you running serial or parallel? Your output indicates serial. Can you try parallel?

For some reason I was not able to specify a master and slave in the meshfile as well. The format should be:

```
periodic
1 1
1 4
```
Where the first number is the number of boundaries and then you specify the master boundary and then the slave boundaries.

 ```
periodic
number-of-masters master-1 master-2 ... master-n
number-of-slaves slave-1 slave-2 ... slave-n
```
This does not seem to work now. I have an idea why, it seems that some part of the code is (intentionally?) left out? If I fix it I get another error. I can look at this later.

![Screenshot from 2021-11-16 11-09-17](https://user-images.githubusercontent.com/69582468/141965939-9a783fbb-c7eb-41eb-bd29-d4e36f0e929c.png)

**Comment by marc-85** [comment]
Hi @JacobLotz,
Thanks again for your support. I have managed to run the example from the branch `nurbs-knot2edge` using my mesh. 

Now, I am trying to compile my example against branch `nurbs-knot2edge` and I still get an error. This error, however,  happens when trying to create a `ParMesh` from the NURBS mesh. So, in the following code, the error happens in the last line:
```cpp
Mesh *old_mesh = new Mesh(mesh_file, 1, 1);
int dim = old_mesh->Dimension();
Array<int> master(2), slave(2);
master[0] = 1;
master[1] = 2;
lave[0] = 4;
lave[1] = 3;
old_mesh->NURBSext->ConnectBoundaries(master,slave);
ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, *nurbs_mesh);
```

Is that allowed?

**Comment by JacobLotz** [comment]
If I am honest, this will probably outside my current knowledge. So I am not entirely sure what is happening here. I have the idea that this error does not result from a mesh being periodic (or not) or a mesh which is being made periodic. As validation: Do you get an error when running the same without a periodic boundary condition?

I would suggest to use the nurbs-knot2edge branch and follow the examples in miniapps/nurbs when in doubt. Kind of as you did.

Two things I just notice in your example. In 
```
ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, *nurbs_mesh);
```
you do not use the mesh which you have just made periodic right? From what I understand it is initialized in somewhere else. There is also a typo in the lines:
```
lave[0] = 4;
lave[1] = 3;
```
I think it is good to check if you are using:
```
ParMesh(MPI_COMM_WORLD, *nurbs_mesh);
```
correctly as I cannot see what `nurbs_mesh` is. 

As I will be out of office for the coming two weeks, I will probably not able to respond soon. I'm sorry for that!

**Comment by marc-85** [comment]
Hi @JacobLotz,
thanks again for your response. Apologies for the typos in the code. I put them there when copying from my code. To be more clear here is what happens.
This runs:
```cpp
Mesh *old_mesh = new Mesh(mesh_file, 1, 1);
int dim = old_mesh->Dimension();
Array<int> master(2), slave(2);
master[0] = 1;
master[1] = 2;
slave[0] = 4;
slave[1] = 3;
//old_mesh->NURBSext->ConnectBoundaries(master,slave);
ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, *old_mesh);
```

but this fails in the last line:
```cpp
Mesh *old_mesh = new Mesh(mesh_file, 1, 1);
int dim = old_mesh->Dimension();
Array<int> master(2), slave(2);
master[0] = 1;
master[1] = 2;
slave[0] = 4;
slave[1] = 3;
old_mesh->NURBSext->ConnectBoundaries(master,slave);
ParMesh *pmesh = new ParMesh(MPI_COMM_WORLD, *old_mesh);
```

**Comment by tzanio** [comment]
@IdoAkkerman, can you help @marc-85 ?
