### ISSUE TITLE
Improve the error handling for most solvers

### ISSUE THREAD

**Issue by adam-sim-dev** [mfem/mfem#4813]
Most MFEM implemented solvers handle errors using `MFEM_VERIFY` and `MFEM_ASSERT`. Solver::`Mult (const Vector &x, Vector &y)` is a void function. When one solver is used as the precondition for another, the error in precondition solving won't be propagated to the outer solving process. So, the outer main solver will continue without error handling, while it's expected to return or stop early.

So I suggest improving the error handling for most solvers. An error code should be returned, just like `PetscErrorCode  KSPSolve(KSP ksp,Vec b,Vec x)`  for the native PETSc solvers.

**Comment by najlkin** [comment]
This is something for discussion, but let me add a few things:

- Severe errors are checked in preconditioners like anywhere else, `MFEM_VERIFY/ASSERT` abort run from any place.
- Convergence can be checked for `IterativeSolver`s, you may also add printing of errors to check the progress.
- Preconditioners typically work with a limited number of iteration (most typically one), so convergence cannot be expected and the flag must be intentionally ignored.
- The only space for improvement I see with, for example, positivity check in `CGSolver`, which is mentioned in the console, but is not distinguishable from just non-converged solution. These errors could be caught and reported to the outer solver so it could stop if detected 🤔

**Comment by adam-sim-dev** [comment]
> * Severe errors are checked in preconditioners like anywhere else, `MFEM_VERIFY/ASSERT` abort run from any place.


`MFEM_VERIFY/ASSERT` abort run from any place troubles me because I solved several problems successively. For some coefficient, the solver failed, while when I increased the coefficient, the solver should succeed.

**Comment by najlkin** [comment]
`MFEM_VERIFY/ASSERT` errors should not be ignored. You need to debug the code and find the real source of the problems. One common source of troubles spuriously appearing depending on the coefficient values is the sparsity pattern of the matrices. If you assemble/finalize matrix with `skip_zeros`, small value entries are eliminated, which can be due to the value of the coefficient. Turning off `skip_zeros` should solve this.

**Comment by adam-sim-dev** [comment]
> `MFEM_VERIFY/ASSERT` errors should not be ignored. You need to debug the code and find the real source of the problems. One common source of troubles spuriously appearing depending on the coefficient values is the sparsity pattern of the matrices. If you assemble/finalize matrix with `skip_zeros`, small value entries are eliminated, which can be due to the value of the coefficient. Turning off `skip_zeros` should solve this.

Setting skip_zeros=0 does not fix the problem for me. My application is similar to the H(curl) problem in ex22p, omega is small, and c is small in parts of the domain. I use PCG/AMS to solve the preconditioning system. The error message is `PCG: The operator is not positive definite.` I then use MINRES. MINRES reports `--> beta = -nan`. For high-order FE, this problem is more serious (compared to edge element, even larger c values caused errors). This phenomenon has bothered me for several years, and I also want to know why. For a fixed omega, sometimes I could work around the issue using large c values. However, sometimes larger c does not work.

**Comment by hughcars** [comment]
Given the operation is symmetric, i.e. the integral looks something like `sum_i w_i f_i^2`, is it possible that this is from using gauss quadratures with negative weights? This reminds me a lot of the behaviour of CFD solvers when trying to avoid negative densities and pressures etc. when working with anisotropic meshes. This would be more of a problem with higher order basis functions, which aligns with your experience, as I believe lower order schemes generally have fewer negative weights.

**Comment by adam-sim-dev** [comment]
> Given the operation is symmetric, i.e. the gauss-quadrature integral looks something like `sum_i w_i f_i^2`, is it possible that this is from using gauss quadratures with negative weights? This reminds me a lot of the behaviour of CFD solvers when trying to avoid negative densities and pressures etc. when working with anisotropic meshes. This would be more of a problem with higher order basis functions, which aligns with your experience, as I believe lower order schemes generally have fewer negative weights.

I have no idea about this.
